const app = require('./server')
const instanceController = require('./controller/instanceController')
const authLoginController = require('./controller/authLoginController')
const accountsController = require('./controller/accountsController')
const journeysController = require('./controller/journeysController')
const templatesController = require('./controller/templatesController')

app.get('/api/instance', instanceController.getInstance)
app.post('/auth/login', authLoginController.postLogin)
app.get("/auth", authLoginController.auth)
app.get("/accounts", accountsController.getAccount)
app.get("/journeys", journeysController.getListJourneys)
app.patch("/journeys", journeysController.patchListJourneys)
app.patch("/journeys/visual-layout", journeysController.visualLayout)
app.get("/journeys/:id", journeysController.getJourneyId)
app.get("/templates", templatesController.getTemplate)