import {
  API_BASE_URL_KEY, 
  REACT_APP_APP_VESION, 
  REACT_APP_API_BASE_URL,
  REACT_APP_FAKE_SERVER_URL,
  REACT_APP_JSON_SERVER_URL,
  REACT_APP_POSTHOG_KEY,
  REACT_APP_POSTHOG_HOST,
  REACT_APP_WS_BASE_URL,
  REACT_APP_JOURNEY_ONBOARDING,
  REACT_APP_ONBOARDING_API_KEY,
} from "config";

export default {
  APP_VERSION: REACT_APP_APP_VESION,
  API_BASE_URL: API_BASE_URL_KEY,
  FAKE_SERVER_URL: REACT_APP_FAKE_SERVER_URL,
  JSON_SERVER_URL: REACT_APP_JSON_SERVER_URL,
  POSTHOG_KEY: REACT_APP_POSTHOG_KEY,
  POSTHOG_HOST: REACT_APP_POSTHOG_HOST,
  WS_BASE_URL: REACT_APP_WS_BASE_URL,
  JOURNEY_ONBOARDING: REACT_APP_JOURNEY_ONBOARDING,
  ONBOARDING_API_KEY: REACT_APP_ONBOARDING_API_KEY,
  storageKeys: {
    USER_DATA: "userData",
  },
};
