module.exports = {
  getAccount(req, res) {
    const account = {
      "email": "laerciopesa30@hotmail.com",
      "password": "$2a$10$r1l8sMtsmcOflxQWkqK9AefPLLE1jYcQxhdmOlRGa1nYuo5WyTGxy",
      "firstName": "Laercio Carlos",
      "lastName": "Nogueira",
      "lastLoginAt": "2024-05-02T01:51:56.652Z",
      "verified": true,
      "onboarded": false,
      "expectedOnboarding": [],
      "currentOnboarding": [],
      "accountCreatedAt": "2024-04-30T02:37:59.910Z",
      "id": "1e0ad92f-c4fb-4e40-9778-7432740a19a5",
      "secondtillunblockresend": null,
      "workspace": {
        "id": "80166b1c-3d28-49e4-b720-e74d35b6232b",
        "name": "knowmap workspace",
        "timezoneUTCOffset": "UTC-03:00",
        "apiKey": "WhsdNBjZ1jzKLp7LhJaTBVrMT34jqTkocux0a1lw",
        "plan": "free",
        "mailgunAPIKey": null,
        "sendingDomain": null,
        "sendingEmail": null,
        "sendingName": null,
        "slackTeamId": null,
        "posthogApiKey": null,
        "posthogProjectId": null,
        "posthogHostUrl": null,
        "posthogSmsKey": null,
        "posthogEmailKey": null,
        "posthogFirebaseDeviceTokenKey": null,
        "firebaseCredentials": null,
        "emailProvider": null,
        "testSendingEmail": null,
        "testSendingName": null,
        "messagesSent": 0,
        "freeEmailsCount": 3,
        "sendgridApiKey": null,
        "sendgridFromEmail": null,
        "sendgridVerificationKey": null,
        "smsAccountSid": null,
        "smsAuthToken": null,
        "smsFrom": null,
        "posthogSetupped": false,
        "javascriptSnippetSetupped": false,
        "pushPlatforms": {},
        "resendSendingDomain": null,
        "resendAPIKey": null,
        "resendSigningSecret": null,
        "resendSendingName": null,
        "resendSendingEmail": null,
        "mailgunConnections": [],
        "sendgridConnections": [],
        "resendConnections": [],
        "twilioConnections": [],
        "pushConnections": []
      }
    }

    res.json(account)
  },
}